language: python
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true
# command to install dependencies
install:
  - sudo apt-get install libqt4-dev
  - pip3 install PySide2;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - pip3 install -e .
  - pip3 install -r test-requirements.txt
# command to run tests
script: pytest
